#!/usr/bin/env bash
if ["$#" -lt 3];then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	path_to_file="$1"
	ip="$2"
	user="$3"
	path_to_ssh_key="$4"

	ssh -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$user@$ip":~/
fi

if ["$?" -eq 0];then
	echo "File successfully transfered"
else
	echo "Error exist"
fi  
