#!/usr/bin/env bash
#Transfer file to remote server
if [$# -lt 3];then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no $0 $1 $3@$2 -i $4:~
fi
