#!/usr/bin/env bash
#install Nginx

apt-get update
apt-get install -y nginx

echo "service {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	location = /{
		echo 'Hello World';
	}
}" > /etc/nginx/sites-available/default
service nginx start
