#!/usr/bin/env bash
#Install Nginx

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to listen on port 80 and serve the index.html file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
