#!/usr/bin/env bash
#Redirection file

sudo apt-get update -y
sudo apt-get install -y nginx

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak


sed -i '/server_name _;/a \ location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n  }' | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
