#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx and setting up redirection

# Update package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Start nginx service
sudo service nginx start

# Create new index file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Set up /redirect_me to redirect to a YouTube video
sudo sed -i '/^server {/a \       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

