#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.


hour=0
minute=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
	if [ $hour -gt 0 ]
	then
            echo "$hour"
        fi
        echo "$minute"
        ((minute++))
    done
    minute=1
    ((hour++))
done

